# Generated by Django 4.2.13 on 2024-07-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
