# Generated by Django 4.2.13 on 2024-07-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_join_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='updated_on',
        ),
    ]
