# Generated by Django 4.2.13 on 2024-07-23 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_joinrequest_alter_join_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
