# Generated by Django 4.2.13 on 2024-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_steps_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(choices=[(1, 5), (2, 10), (3, 15), (4, 20), (5, 30), (6, 45), (7, 60), (8, 120)], default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='freezable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(choices=[(1, 5), (2, 10), (3, 15), (4, 20), (5, 25), (6, 30)], default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 4), (4, 8)], default=1),
        ),
    ]
